Develop driver for INA3221 (#20)
* Initial commit

* Functionally complete(?) ina driver

* Need multi-byte i2c reads

* Add device ID read. Use multi-byte reads

* comments`

* rebased new changes

* finished linting

* Add alert threshold sets and multibyte i2c writes

* do template i2c write for TCA

Co-authored-by: Marco Kurzynski <marcokurzynski@icloud.com>

diff --git a/bloop-dev b/bloop-dev
--- a/bloop-dev
+++ b/bloop-dev
@@ -58,21 +58,43 @@ EOF
 elif [ "$1" == "cross" ]; then
     $0 clean
     mkdir build && cd build
-    if [ ! -d /opt/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf ]; then
-	wget -c \
-    https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz \
-    -P /tmp/
-	if [ $? -ne 0 ]; then
-		echo "Failure to get arm-linux-gnueabihf"
-	fi
-	sudo tar xf /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/
+    if [ $(arch) == "aarch64" ]; then
 
-	rm /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
+      if [ ! -d /opt/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf ]; then
+  	wget -c \
+      https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz \
+      -P /tmp/
+  	if [ $? -ne 0 ]; then
+  		echo "Failure to get arm-linux-gnueabihf"
+  	fi
+  	sudo tar xf /tmp/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz -C /opt/
+
+  	rm /tmp/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz
+      fi
+      toolchain='./toolchains/beaglebone_aarch64.cmake'
+
+    elif [ $(arch) == "x86_64" ]; then
+
+      if [ ! -d /opt/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf ]; then
+  	wget -c \
+      https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz \
+      -P /tmp/
+  	if [ $? -ne 0 ]; then
+  		echo "Failure to get arm-linux-gnueabihf"
+  	fi
+  	sudo tar xf /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/
+
+  	rm /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
+      fi
+      toolchain='./toolchains/beaglebone.cmake'
     fi
+
+
+
     if [ "$2" == "test" ]; then
-        cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/beaglebone.cmake -DTEST=ON -Wno-dev ..
+        cmake -DCMAKE_TOOLCHAIN_FILE=$toolchain -DTEST=ON -Wno-dev ..
     else
-        cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/beaglebone.cmake ..
+        cmake -DCMAKE_TOOLCHAIN_FILE=$toolchain ..
     fi
 
     if [ $? -ne 0 ]; then
