build stuff works now

diff --git a/bloop-dev b/bloop-dev
--- a/bloop-dev
+++ b/bloop-dev
@@ -43,6 +43,52 @@ if [ "$1" == "build" ]; then
         `======/
 EOF
 
+elif [ "$1" == "cross" ]; then
+    $0 clean
+    mkdir build && cd build
+    if [ ! -d /opt/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf ]; then
+	cd /tmp/
+	wget -c https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
+	if [ $? -ne 0 ]; then
+		echo "Failure to get arm-linux-gnueabihf"
+	fi
+	sudo tar xf gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/
+
+	rm gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
+    fi
+    cmake -DCMAKE_TOOLCHAIN_FILE=./toolchains/beaglebone.cmake ..
+
+    if [ $? -ne 0 ]; then
+        echo "Awwwww geeeeez rick, CMake failed"
+        exit 1
+    fi
+    
+    make
+
+    if [ $? -ne 0 ]; then
+        echo "Awwwww geeeeez rick, Make failed"
+        exit 1
+    fi
+    cat <<'EOF'
+        ___
+    . -^   `--,      
+   /# =========`-_   
+  /# (--====___====\ 
+ /#   .- --.  . --.| 
+/##   |  * ) (   * ),
+|##   \    /\ \   / |
+|###   ---   \ ---  |
+|####      ___)    #|
+|######           ##|
+ \##### ---------- / 
+  \####           (  
+   `\###          |  
+     \###         |  
+      \##        |   
+       \###.    .)   
+        `======/
+EOF
+
 elif [ "$1" == "clean" ]; then
 	rm -rf build
 	rm -rf out
