fixed formatting

diff --git a/bloop-dev b/bloop-dev
--- a/bloop-dev
+++ b/bloop-dev
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 ROOT_DIR=$(dirname $0)
 PYTHON_ENV=$ROOT_DIR/.env
 PYBIN=$PYTHON_ENV/bin
@@ -8,13 +7,13 @@ PRE_COMMIT=$PYBIN/pre-commit
 PYTHON=$PYBIN/python
 
 prep() {
-    ./btf/i2cinit.sh && ./btf/caninit.sh 2> /dev/null
-    STUB_BUS=$(awk '{ if ($4 ~ /stub/) { print substr($1,5) }}' <(i2cdetect -l) 2> /dev/null)
-    if [ -z ${STUB_BUS} ]; then
-      ARGS="-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
-    else
-      ARGS="-DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DSTUB_BUS=${STUB_BUS}"
-    fi
+  ./btf/i2cinit.sh && ./btf/caninit.sh 2> /dev/null
+  STUB_BUS=$(awk '{ if ($4 ~ /stub/) { print substr($1,5) }}' <(i2cdetect -l) 2> /dev/null)
+  if [ -z ${STUB_BUS} ]; then
+    ARGS="-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
+  else
+    ARGS="-DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DSTUB_BUS=${STUB_BUS}"
+  fi
 }
 
 #credit: https://emojicombos.com/rick-and-morty-ascii-art
@@ -42,101 +41,92 @@ echo -e '\033[32m⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⡤⣠⣤⣴⡾⠛
 }
 
 oops() {
-    echo -e "\033[1;42mError:\033[0m \033[1;32m${*}\033[0m" >&2
-    exit 1
+  echo -e "\033[1;42mError:\033[0m \033[1;32m${*}\033[0m" >&2
+  exit 1
 }
 
-
 if [ "$1" == "build" ]; then
-    prep
+  prep
 
-    [ -d build ] || mkdir build
-    pushd build
+  [ -d build ] || mkdir build
+  pushd build
 
-    cmake ${ARGS} ..
+  cmake ${ARGS} ..
+  [ $? -ne 0 ] && oops "CMake failed"
+  make
+  [ $? -ne 0 ] && oops "Make failed"
 
-    [ $? -ne 0 ] && oops "CMake failed"
-
-    make
-
-    [ $? -ne 0 ] && oops "Make failed"
-
-    popd
-    sudo ./out/gtests
-    [ $? -eq 0 ] && pickle_rick || oops "GTests failed"
+  popd
+  sudo ./out/gtests
+  [ $? -eq 0 ] && pickle_rick || oops "GTests failed"
 
 elif [ "$1" == "cross" ]; then
-    prep
+  prep
 
-    [ -d build ] || mkdir build
-    pushd build
+  [ -d build ] || mkdir build
+  pushd build
 
 
-    if [ $(uname -m) == "aarch64" ]; then
-        if [ ! -d /opt/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf ]; then
-  	        wget -c \
-              https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz \
-              -P /tmp/
+  if [ $(uname -m) == "aarch64" ]; then
+    if [ ! -d /opt/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf ]; then
+      wget -c \
+        https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz \
+        -P /tmp/
 
-  	        [ $? -ne 0 ] && oops "Failure to get arm-linux-gnueabihf"
+      [ $? -ne 0 ] && oops "Failure to get arm-linux-gnueabihf"
 
-  	        sudo tar xf /tmp/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz -C /opt/
-  	        rm /tmp/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz
-        fi
-        TOOLCHAIN='./toolchains/beaglebone_aarch64.cmake'
-
-    elif [ $(uname -m) == "x86_64" ]; then
-        if [ ! -d /opt/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf ]; then
-        	  wget -c \
-              https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz \
-              -P /tmp/
-
-        	  [ $? -ne 0 ] && oops "Failure to get arm-linux-gnueabihf"
-
-        	  sudo tar xf /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/
-        	  rm /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
-        fi
-        TOOLCHAIN='./toolchains/beaglebone.cmake'
+      sudo tar xf /tmp/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz -C /opt/
+      rm /tmp/gcc-arm-10.3-2021.07-aarch64-arm-none-linux-gnueabihf.tar.xz
     fi
+    TOOLCHAIN='./toolchains/beaglebone_aarch64.cmake'
 
-    cmake ${ARGS} -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN ..
+  elif [ $(uname -m) == "x86_64" ]; then
+    if [ ! -d /opt/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf ]; then
+      wget -c \
+        https://releases.linaro.org/components/toolchain/binaries/6.5-2018.12/arm-linux-gnueabihf/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz \
+        -P /tmp/
 
-    [ $? -ne 0 ] && oops "CMake failed"
+      [ $? -ne 0 ] && oops "Failure to get arm-linux-gnueabihf"
 
-    make
+      sudo tar xf /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/
+      rm /tmp/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf.tar.xz
+    fi
+    TOOLCHAIN='./toolchains/beaglebone.cmake'
+  fi
 
-    [ $? -ne 0 ] && oops "Make failed" || pickle_rick
+  cmake ${ARGS} -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN ..
+
+  [ $? -ne 0 ] && oops "CMake failed"
+  make
+  [ $? -ne 0 ] && oops "Make failed" || pickle_rick
 
 elif [ "$1" == "clean" ]; then
-	rm -rf build
-	rm -rf out
-	rm -rf coverage
-	echo "clean finished"
+  rm -rf build
+  rm -rf out
+  rm -rf coverage
+  echo "clean finished"
 
 elif [ "$1" == "setup" ]; then
-    sudo apt update
-    sudo apt install \
-        python3 \
-        virtualenv \
-        clang-format \
-        cppcheck \
-        i2c-tools \
-        linux-modules-extra-$(uname -r)
+  sudo apt update
+  sudo apt install \
+    python3 \
+    virtualenv \
+    clang-format \
+    cppcheck \
+    i2c-tools \
+    linux-modules-extra-$(uname -r)
 
-    virtualenv -p python3 $PYTHON_ENV
+  virtualenv -p python3 $PYTHON_ENV
+  $PYBIN/pip install pre-commit
+  $PRE_COMMIT install
 
-    $PYBIN/pip install pre-commit
-
-    $PRE_COMMIT install
-
-    git submodule update --init --recursive
-
+  git submodule update --init --recursive
 
 elif [ "$1" == "lint" ]; then
-    $PRE_COMMIT run -a
+  $PRE_COMMIT run -a
 
 elif [ "$1" == "autocode" ]; then
-    $PYTHON $ROOT_DIR/autocoding/autocode.py
-else
-    oops "Usage $0 {clean, build, cross, setup, lint, autocode}"
+  $PYTHON $ROOT_DIR/autocoding/autocode.py
+  else
+  oops "Usage $0 {clean, build, cross, setup, lint, autocode}"
 fi
